baseURL: https://jblew.pl/
defaultContentLanguage: en
theme: jblew.pl-on-papermod
enableGitInfo: true
enableRobotsTXT: true
# googleAnalytics: UA-...

staticDir:
  - static

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: category
  tag: tags

params:
  env: production
  defaultTheme: auto
  description: Blog of JÄ™drzej (pronounce J-J) Lewandowski. Doctor, software developer and behaviorist.
  homeMetaContent: Blog of JÄ™drzej (pronounce J-J) Lewandowski. Doctor, software developer and behaviorist.
  displayFullLangName: true
  ShowReadingTime: true
  socialIcons: # optional
    - name: github
      url: "https://github.com/Jblew"
    - name: linkedin
      url: "https://www.linkedin.com/in/j%C4%99drzej-lewandowski/"
    - name: 
      text: CodersRank
      url: "https://profile.codersrank.io/user/jblew"
  images:
    - "/img/jedrzej-lewandowski-600.jpg"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006

languages:
  pl:
    languageName: Polski
    LanguageName: ðŸ‡µðŸ‡± Polski
    title: JÄ™drzej Lewandowski
    homeInfoParams:
      Title: JÄ™drzej B. Lewandowski
      Image:
        Alt: JÄ™drzej BogumiÅ‚ Lewandowski
        Src: "/img/jedrzej-lewandowski-600.jpg"
      Content: |
        CzeÅ›Ä‡, jestem JÄ™drzej. Z powoÅ‚ania jestem programistÄ…, ale z zamiÅ‚owania 
        koÅ„czÄ™ trening do bycia lekarzem (w czerwcu). To sÄ… moje kroniki. TwÃ³rczoÅ›Ä‡ od 2009 do teraz. Jestem dumny z bycia katolikiem.
        Chcesz wiedzieÄ‡ wiÄ™cej? => [CV JÄ™drzeja](/cv). Zapraszam [do kontaktu](/pl/contact) 
    menu:
      main:
        - name: 'Blog'
          url: '/pl/'
        - name: 'Kontakt'
          url: '/pl/contact'
        - name: 'CV'
          url: '/cv'
        - name: 'Archiwum'
          url: '/pl/archives'
        - name: 'Kategorie'
          url: '/pl/category'
    header:
      supertitle: Ciekawe przypadki
      midtitle1: JÄ™drzeja
      midtitle2: Lewandowskiego
      subtitle: Programista, moÅ¼e bÄ™dÄ™ lekarzem
      link: /pl
    profilePhoto: /img/jedrzej-lewandowski-600.jpg
    profileText: 'CzeÅ›Ä‡, jestem JÄ™drzej. Student 6 roku medycyny, programista senior fullstack (typescript / vue / node / golang). Ten blog jest mojÄ… kronikÄ….'
    weight: 2
    author: JÄ™drzej B. Lewandowski
    copyright: |
        Copyright &copy; 2009-now by JÄ™drzej Lewandowski.
        <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
        <img alt="Creative Commons License" style="border-width:0;display:inline-block;" src="https://i.creativecommons.org/l/by/4.0/80x15.png" />
        </a>
        This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

  en:
    languageName: English
    LanguageName: ðŸ‡¬ðŸ‡§ English
    title: JB Lewandowski (J-J)
    homeInfoParams:
      Title: JB Lewandowski
      Image:
        Alt: JÄ™drzej BogumiÅ‚ Lewandowski
        Src: "/img/jedrzej-lewandowski-600.jpg"
      Content: |
        Hi, I'm JÄ™drzej (pronounced J-J). My calling is software development, but I'm also a hobbyst med student,
        finishing the training in June. Here I present my entire chronicles to you. From 2009 till now. I'm proud to be a Catholic.
        Want to know more? => [CV of J-J](/cv). Any [contact](/contact) is welcome
    menu:
      main:
        - name: 'Blog'
          url: '/'
        - name: 'Contact'
          url: '/contact'
        - name: 'CV'
          url: '/cv'
        - name: 'Archives'
          url: '/archives'
        - name: 'Categories'
          url: '/category'
    header:
      supertitle: Curious case of
      midtitle1: JÄ™drzej (J-J)
      midtitle2: Lewandowski
      subtitle: MDoctorist, programmist & behaviourist
      link: /en
    author: JB Lewandowski
    profilePhoto: /img/jedrzej-lewandowski-600.jpg
    profileText: 'Hi, Iâ€™m JÄ™drzej. 6th year medical student, fullstack software developer and behavioural design passionate. This blog is a chronicle of my activity.'
    weight: 1
    params:
    copyright: |
        Copyright &copy; 2009-now by JÄ™drzej Lewandowski. 
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
        <img alt="Licencja Creative Commons" style="border-width:0;display:inline-block;" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
        </a>
        Ten utwÃ³r jest dostÄ™pny na <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">licencji Creative Commons Uznanie autorstwa-Na tych samych warunkach 4.0 MiÄ™dzynarodowe</a>.

permalinks:
  posts: /:year/:month/:title/
  archiveyearly: /:year/

imaging:
  quality: 99

menu:
  categories:
    - identifier: bezpieczenstwo
      title: "BezpieczeÅ„stwo (PL)"
      url: /pl/category/bezpieczenstwo
    - identifier: administracja
      title: Administracja (PL)
      url: /pl/category/administracja
    - identifier: elektronika
      title: Elektronika (PL)
      url: /pl/category/elektronika
    - identifier: fun
      title: Fun (PL)
      url: /pl/category/fun
    - identifier: inne
      title: Inne (PL)
      url: /pl/category/inne
    - identifier: java
      title: Java (PL)
      url: /pl/category/java
    - identifier: programowanie
      title: Programowanie (PL)
      url: /pl/category/programowanie
    - identifier: webmastering
      title: Webmastering (PL)
      url: /pl/category/webmastering
    - identifier: blockchain
      title: Blockchain (PL)
      url: /pl/category/blockchain
    - identifier: katolicyzm
      title: Katolicyzm (PL)
      url: /pl/category/katolicyzm
    - identifier: polski
      title: Polski (PL)
      url: /pl/category/polski
    - identifier: technologia
      title: Technologia (PL)
      url: /pl/category/technologia

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2